### ISSUE TITLE
Meaningful unit test coverage - Course page

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#105]
The course page (https://wayfair.github.io/awesome-learning/courses/Promises/) contains all of our lessons within a specific course. A unit test to vet the following would be great!

- All individual lessons passed to it are displayed, in addition to the relevant content as queried by GraphQL
- All tags related to this lesson are displayed under the lesson content

**Comment by fernandopiniani** [comment]
I'll do it.

**Comment by SheaBelsky** [comment]
@fernandopiniani It's all yours! Thank you for picking this up!

**Comment by fernandopiniani** [comment]
Where do you prefer to put the tests files? Separated in tests directory, or in the same dir as the component file?

**Comment by fernandopiniani** [comment]
Do you know why `.only` or `beforeAll` hooks are not working? I'm not used to Jest, so maybe it's just some newbie mistake, but I couldn't achieve to make them work...

**Comment by fernandopiniani** [comment]
Hey, check it out. I created some tests covering Course component. Please let me know if you need anything else or if there's some mistake (I'm new to frontend testing).

**Comment by fernandopiniani** [comment]
I found some errors throwing when running tests. I openend an issue reporting it: https://github.com/wayfair/awesome-learning/issues/123

**Comment by SheaBelsky** [comment]
Resolved by #125
