### ISSUE TITLE
Meaningful unit test coverage - ContentSection

### ISSUE THREAD

**Issue by rellison192** [wayfair/awesome-learning#106]
## Problem
As part of issue #59, all snapshots tests where removed. We would now like to replace these snapshots with a more meaningful unit test.

## Acceptance Criteria

Using @testing-library/react create a test for `ContentSection.js` found in `src/components/ContentSection/`

**Comment by SheaBelsky** [comment]
@rellison192 Can you speak a little more about the acceptance criteria for this component? What kinds of unit tests are you thinking of?

**Comment by rellison192** [comment]
feel free to add any details you think are missing @SheaBelsky  :)

**Comment by laura-barluzzi** [comment]
I'm happy to work on this.

**Comment by laura-barluzzi** [comment]
@rellison192 @SheaBelsky since nobody claimed this issue I went ahead and worked on it and I opened a PR.
