### ISSUE TITLE
Meaningful unit test coverage - HowTo

### ISSUE THREAD

**Issue by rellison192** [wayfair/awesome-learning#110]
## Problem
As part of issue #59, all snapshots tests where removed. We would now like to replace these snapshots with a more meaningful unit test.

## Acceptance Criteria

Using @testing-library/react create a test for `HowTo.js` found in `src/components/HowTo/HowTo.js`

**Comment by briceyokoyama** [comment]
Can I work on this one?

**Comment by nicolabuckhurst** [comment]
@briceyokoyama Are you working in this?

**Comment by anuk79** [comment]
@briceyokoyama Hey, are you working on this? If not, can I work on this? I would like to contribute to this - @nicolabuckhurst
