### ISSUE TITLE
Meaningful unit test coverage - Landing

### ISSUE THREAD

**Issue by rellison192** [wayfair/awesome-learning#112]
## Problem
As part of issue #59, all snapshots tests where removed. We would now like to replace these snapshots with a more meaningful unit test.

## Acceptance Criteria

Using @testing-library/react create a test for `Landing.js` found in `src/components/Landing/`

**Comment by mattstates** [comment]
I would like to take this one.

**Comment by SheaBelsky** [comment]
@mattstates This one is yours, thanks for picking it up!
