### ISSUE TITLE
Meaningful unit test coverage - Lesson

### ISSUE THREAD

**Issue by rellison192** [wayfair/awesome-learning#115]
## Problem
As part of issue #59, all snapshots tests where removed. We would now like to replace these snapshots with a more meaningful unit test.

## Acceptance Criteria

Using @testing-library/react create a test for `Lesson.js` found in `src/components/Lesson/`

**Comment by nicolabuckhurst** [comment]
I'll try this one if noones working on it

**Comment by SheaBelsky** [comment]
@nicolabuckhurst This one's all you, thank you for picking it up!
