### ISSUE TITLE
Meaningful unit test coverage - Link

### ISSUE THREAD

**Issue by rellison192** [wayfair/awesome-learning#117]
## Problem
As part of issue #59, all snapshots tests where removed. We would now like to replace these snapshots with a more meaningful unit test.

## Acceptance Criteria

Using @testing-library/react create a test for `Link.js` found in `src/components/Link/`

**Comment by paperlambda** [comment]
@rellison192 I would love to take this one

**Comment by SheaBelsky** [comment]
@paperlambda This issue's all yours, thanks for picking it up!
