### ISSUE TITLE
Meaningful unit test coverage - Pagination

### ISSUE THREAD

**Issue by rellison192** [wayfair/awesome-learning#119]
## Problem
As part of issue #59, all snapshots tests where removed. We would now like to replace these snapshots with a more meaningful unit test.

## Acceptance Criteria

Using @testing-library/react create a test for `Pagination.js` found in `src/components/Pagination/`

**Comment by laura-barluzzi** [comment]
I'd like to add the tests for this if nobody else is working on it.

**Comment by rellison192** [comment]
Awesome! Thanks for picking it up.
