### ISSUE TITLE
Meaningful unit test coverage - Text

### ISSUE THREAD

**Issue by rellison192** [wayfair/awesome-learning#120]
## Problem
As part of issue #59, all snapshots tests where removed. We would now like to replace these snapshots with a more meaningful unit test.

## Acceptance Criteria

Using @testing-library/react create a test for `Text.js` found in `src/components/Text/`

**Comment by bagshik** [comment]
Hey there, I can take this one. Which cases need to be covered?

**Comment by SheaBelsky** [comment]
Thanks for picking this up @bagshik ! I'm thinking tests around the following would be good:

- Font sizes are passed down and result in the appropriate class getting set
- Children to the Text component are properly mounted by the Text component

**Comment by SheaBelsky** [comment]
@bagshik It looks like @Slide109 put up an MR on this issue recently. I'm going to assign them, and unassign you, but you're more than welcome to put your name on another issue!

**Comment by SheaBelsky** [comment]
Closed by #121
