### ISSUE TITLE
Link component is throwing a warning.

### ISSUE THREAD

**Issue by fernandopiniani** [wayfair/awesome-learning#123]
**Describe the bug**
When running tests with `npm run test`, I'm getting the following error:

> console.error node_modules/react-dom/cjs/react-dom.development.js:545
>       Warning: <Link /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
>           in Link (created by StyledLink)
>           in StyledLink (created by CourseCard)
>           in h3 (created by Block)
>           in Block (created by CourseCard)
>           in li (created by CourseCard)
>           in CourseCard
> 

**To Reproduce**
1. Run `npm run test`

**Expected behavior**
This error should not appear. I believe this is happing because the following block of code:

```
const className = cx("Link", {
    "is-button": isButton,
    "is-block": isBlock,
    [`Link--${variation}`]: variation && !isButton
  });
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - Terminal

**Comment by fernandopiniani** [comment]
I'll have it.

**Comment by Lawrence4code** [comment]
I'd like to work on this, please.

**Comment by fernandopiniani** [comment]
> I'd like to work on this, please.

I'm kinda stuck on this... It seems to be related with gatsby, which is exporting a string instead of a react component. If you know how to solve it, go on.

**Comment by Cooperbuilt** [comment]
It's all yours @Lawrence4code

**Comment by SheaBelsky** [comment]
I've opened this issue on the Gatsby repo:

https://github.com/gatsbyjs/gatsby/issues/20523

**Comment by sidharthachatterjee** [comment]
Thanks for opening the issue. Opened a PR to fix it for you. 

❤️  from Gatsby
