### ISSUE TITLE
package-lock.json has merge conflict markers

### ISSUE THREAD

**Issue by tsargent** [wayfair/awesome-learning#154]
**Describe the bug**

It looks like [this PR](https://github.com/wayfair/awesome-learning/pull/150 ) brought in an unresolved merge conflict in package-lock.json

**To Reproduce**
see 
https://github.com/wayfair/awesome-learning/pull/150/commits/bdfe7da0adbb49a12c1beb116a600cb04f6437f5

**Comment by SheaBelsky** [comment]
Closed by #155
