### ISSUE TITLE
Broken pre-read links on lessons

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/awesome-learning#17]
**Describe the bug**
There are broken pre-read links in our lesson pages.

**To Reproduce**
1. Go to https://wayfair.github.io/awesome-learning/courses/Testing/intro-to-unit-testing/
2. Click on "5 great reasons for running tests"
4. See 404

**Expected behavior**
These links should open new windows to the desired link.

**Comment by danieluhl** [comment]
I'm not able to reproduce this one, maybe fixed by https://github.com/wayfair/awesome-learning/pull/13

**Comment by Cooperbuilt** [comment]
Looks good now via the fix in #13
