### ISSUE TITLE
[Redesign] Create Global Variables in SCSS

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#175]
## Overview
https://github.com/wayfair/awesome-learning/wiki/Awesome-Learning-2020-Redesign

## Details
We want to pre-define our color variables in an SCSS file that other SCSS files in the Awesome Learning platform will consume. That way, when we refer to a color by its name, we can direct engineers to use a variable instead of referring to a color by its hex/RGB code only.

* `#2B416A` => `$primary-color`
* `#69ADC9` => `$light-accent`
* `#FAFBFB` => `$light-shade`
* `#6A6C7A` => `$dark-accent`
* `#1D1820` => `$dark-shade`

When we implement components such as buttons, cards, links, body text, and more, each of these components will derive from these variables. Update the below file to add these variables. Then, replace things like `$color--base`, `$color--tertiary`, with their new variables.

When doing this, please also remove unused color variables.

https://github.com/wayfair/awesome-learning/blob/master/src/assets/scss/_variables.scss

**Comment by errskipower** [comment]
I'd like to tackle this one!

**Comment by errskipower** [comment]
@SheaBelsky A few questions:

1.  Does this mean to remove all `$color--XXXX` variables or to replace the hex values that are assigned to them?

      > Then, replace things like $color--base, $color--tertiary, with their new variables.

2. What is the `$color--border` color? A border color isn't mentioned in the Figma file, but it's currently being used throughout the `scss`.

3. What should be done about `$color--red` and `$color--white` since they're both being used?

**Comment by SheaBelsky** [comment]
Great questions @errskipower !

1. Replace the hex values that are assigned to them
2. Good callout! I think that color should be appropriate for now. Let's keep that as it is.
3. That shade of red can be left as-is, and the current white variable should also be left as-is.

**Comment by SheaBelsky** [comment]
Closed via #185
