### ISSUE TITLE
[Redesign] Create Clickable Card Component

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#176]
## Overview
https://github.com/wayfair/awesome-learning/wiki/Awesome-Learning-2020-Redesign

## Details
We want to create a Clickable Card component that contains a small amount of content inside of it. See the below UI Mocks for how it should look and function.

https://www.figma.com/file/Q2AvwPeBaAZWhnP9fYNBiW/Awesome-Learning-Redesign?node-id=1%3A4

## Engineering Criteria
* This card should take an _optional_ `href` prop that links to another page. It should also take an _optional_ `onClick` prop that runs a function when the card is clicked. Add unit tests to confirm that `onClick` is executed when the card is clicked.
* Create a Storybook Story for this component, in addition to unit tests. Refer to the link in the Overview of this issue for information on how to create a Storybook and unit tests.

**Comment by ursaregina** [comment]
I can take this issue. This is crahaim @ WF.

**Comment by ursaregina** [comment]
Point of clarification: the mockup shows an icon and some short text, should the component handle that content/styling or should the contents of the card be left to the user?

**Comment by SheaBelsky** [comment]
@ursaregina I think the icon could also be a function of the card (to keep that sort of styling consistent between implementations.) It should be an optional prop that takes just the icon name; it would then be the responsibility of the card to mount the icon (and not the responsibility of an implementor/engineer to do that additional work.) Great callout!

**Comment by ursaregina** [comment]
This is ready for review https://github.com/wayfair/awesome-learning/pull/186

**Comment by SheaBelsky** [comment]
Closed by #186
