### ISSUE TITLE
[Redesign] Create Base Button Component

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#177]
## Overview
https://github.com/wayfair/awesome-learning/wiki/Awesome-Learning-2020-Redesign

## Details
We want to create a Base Button (Primary and Alternate) that can be inherited by other components. This component is _only_ responsible for creating the button and tests, not for hooking it up anywhere.

https://www.figma.com/file/Q2AvwPeBaAZWhnP9fYNBiW/Awesome-Learning-Redesign?node-id=1%3A4

## Engineering Criteria
* See the `LessonButton` and `StyledLink` components for the API of this component. You do not need to change these components in this issue, but refer to them for an API specification. The Base Button should be a brand new component, with brand new unit tests and Storybook stories.
* One new prop to add is that this component should have a `isPlainText` prop; if `true`, the component should appear as a link (and inherit the styling of a link), though it should still function like a button.
* https://github.com/wayfair/awesome-learning/tree/master/src/components/LessonButton
* https://github.com/wayfair/awesome-learning/tree/master/src/components/shared/StyledLink
* Create a Storybook Story for this component, in addition to unit tests. Refer to the link in the Overview of this issue for information on how to create a Storybook and unit tests.

**Comment by ursaregina** [comment]
I can take this ticket.

**Comment by SheaBelsky** [comment]
@ursaregina It's yours!

**Comment by subhash686** [comment]
I am interested to work on this.

**Comment by ursaregina** [comment]
Given that I haven't started, I'm more than happy for you to take it- I can pick up something else when I have time.
