### ISSUE TITLE
[Redesign] Update maximum width of Navigation to stop growing at 1600px

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#178]
## Overview
https://github.com/wayfair/awesome-learning/wiki/Awesome-Learning-2020-Redesign

## Details
Currently, the content of our experience grows as wide as the resolution of the device browsing Awesome Learning. We want to put a maximum possible size on how much to grow at `1600px`.

## Engineering Criteria
* Update the below file to add a `$layout-breakpoint-xl` variable.
* https://github.com/wayfair/awesome-learning/blob/master/src/assets/scss/_variables.scss
* Beyond this breakpoint, the navigation should appear horizontally centered in the page, no matter how much larger the browser grows. Below 1600px, the navigation should shrink in proportion to the resolution of the browser. 
* You'll want to use the CSS `max-width` property here.

**Comment by hyerania** [comment]
I can pickup this issue.

**Comment by hyerania** [comment]
This is ready for review.

**Comment by SheaBelsky** [comment]
Closed by #178
