### ISSUE TITLE
[Redesign] Update maximum width of Layout to stop growing at 1600px

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#179]
## Overview
https://github.com/wayfair/awesome-learning/wiki/Awesome-Learning-2020-Redesign

## Details
Currently, the content of our experience grows as wide as the resolution of the device browsing Awesome Learning. We want to put a maximum possible size on how much to grow at `1600px`.

## Engineering Criteria
* Wait until the variable in #178 is done.
* Beyond `$layout-breakpoint-xl`, the Layout of a page (see `Layout.js`) should appear horizontally centered in the page, no matter how much larger the browser grows. Below 1600px, the Layout should shrink in proportion to the resolution of the browser. 
* You'll want to use the CSS `max-width` property here.

**Comment by hyerania** [comment]
I can work on this issue.

**Comment by SheaBelsky** [comment]
@hyerania You got it!

**Comment by hyerania** [comment]
This is ready for review.

**Comment by SheaBelsky** [comment]
Closed by #190
