### ISSUE TITLE
[Redesign] Create Landing page UI component and template

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#181]
## Overview
https://github.com/wayfair/awesome-learning/wiki/Awesome-Learning-2020-Redesign

## Details
We need to create a UI component and template for our new landing page.

https://www.figma.com/file/Q2AvwPeBaAZWhnP9fYNBiW/Awesome-Learning-Redesign?node-id=18%3A0

## Engineering Criteria
* #180 is dependent on this ticket. The GraphQL query in this file should be written here, then passed into the Featured Course component.
* This ticket is responsible for updating our existing template and UI component for the redesign. You don't need to add anything new yet.
* Rename `index-template.js` to `landing-template.js`, so that the name of the template corresponds with the name of the UI component. Make sure that existing references to the old template name are changed to the new template name.
* Remove the existing content in `Landing.js`. This will eventually be replaced with other Landing page components that will be engineered and integrated separately.

**Comment by chynh** [comment]
I can work on this.

**Comment by SheaBelsky** [comment]
@chynh You got it, thanks!

**Comment by SheaBelsky** [comment]
Closed by #194 , thank you for picking this up again @chynh !
