### ISSUE TITLE
[Redesign] Update SectionTitle component

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#182]
## Overview
https://github.com/wayfair/awesome-learning/wiki/Awesome-Learning-2020-Redesign

## Details
We're changing the typography of the headings on Awesome Learning. We want to update our existing SectionTitle component to have the new styles.

https://www.figma.com/file/Q2AvwPeBaAZWhnP9fYNBiW/Awesome-Learning-Redesign?node-id=1%3A4

## Engineering Criteria
* Update the `SectionTitle` component with new styles based on the UI Mockup
* You will need to add the new Google Font Muli to our Google Font import.
* Make sure the Storybook Story and unit tests are also updated.

**Comment by TomG84** [comment]
I'll pick this one up @SheaBelsky
