### ISSUE TITLE
[Redesign] Add "What is Awesome Learning" and "How to get started" section to Landing

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#183]
## Overview
https://github.com/wayfair/awesome-learning/wiki/Awesome-Learning-2020-Redesign

## Details
We are updating the content of our landing page, and want to use the new information provided in the below UI mocks.

https://www.figma.com/file/Q2AvwPeBaAZWhnP9fYNBiW/Awesome-Learning-Redesign?node-id=18%3A0

## Engineering Criteria
* These are brand new sections that should be added after #181 is done. 
* The icons from Figma were taken from here: https://github.com/sschoger/heroicons-ui
* The "Get Started" button in "How to get started" should go to the Course Catalog

**Comment by juancarlosqr** [comment]
Hi @SheaBelsky I would like to work on this as part of the Hacktoberfest 2020. Thanks!
