### ISSUE TITLE
Broken Link for Implicit Coercion

### ISSUE THREAD

**Issue by xixi743** [wayfair/awesome-learning#201]
Within the "Data Types" course and in the lesson for "Types and Equality", the link for 
Implicit Coercion by YDKJS is broken.

**To Reproduce**
To reproduce, go to [https://wayfair.github.io/awesome-learning/courses/Data-Types/types-and-equality](https://wayfair.github.io/awesome-learning/courses/Data-Types/types-and-equality) and open the pre-read material for Implicit Coercion.

**Expected behavior**
The new link for that resource is located at [https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/types%20%26%20grammar/ch4.md#implicit-coercion](https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/types%20%26%20grammar/ch4.md#implicit-coercion)

**Comment by shayneofficer** [comment]
Looks like this is resolved @SheaBelsky :D, the link works for me :+1:
