### ISSUE TITLE
Meaningful unit test coverage

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#21]
We currently have some Jest unit tests, but not every unit testable file has them. If we can get more coverage on our unit tests, especially for components that are interaction heavy. The `Quiz` component is a good example of a component that could use unit tests (to guard against changing its intended behavior accidentally.)

See [this directory](https://github.com/wayfair/awesome-learning/tree/master/src/components) for all files that *should* have unit tests.

**Comment by Eshno** [comment]
The following tests will be removed [here](https://github.com/wayfair/awesome-learning/pull/84)

```
src/components/Course/Course.test.js
src/components/Course/Tags/Tags.test.js
src/components/Courses/Courses.test.js
src/components/Header/Header.test.js
src/components/Header/Menu/Menu.test.js
src/components/Icon/Icon.test.js
src/components/Layout/Layout.test.js
src/components/Page/Page.test.js
src/components/Pagination/Pagination.test.js
src/components/SectionTitle.test.js
src/components/Text/Text.test.js
src/templates/categories-list-template.test.js
src/templates/category-template.test.js
src/templates/course-template.test.js
src/templates/index-template.test.js
src/templates/not-found-template.test.js
src/templates/page-template.test.js
src/templates/quiz-template.test.js
src/templates/tag-template.test.js
src/templates/tags-list-template.test.js
```

**Comment by Cooperbuilt** [comment]
Im going to close this in favor of the more specific issues we now have on the board
