### ISSUE TITLE
Fix noisy tests

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#31]
**Describe the bug**
We have multiple unit tests that, while not returning errors, are logging to our test suite after being run. This might confuse contributors who are seeing passing tests that return with errors/warnings.

https://travis-ci.org/wayfair/awesome-learning/builds/572909100

**Expected behavior**
Tests should return nothing or an error (and fail the test.)

**Links**
https://travis-ci.org/wayfair/awesome-learning/builds/572909100

**Comment by sowmiyamuthuraman** [comment]
Can i work on this?

**Comment by SheaBelsky** [comment]
Closed via #32
