### ISSUE TITLE
Add ability to return to your last lesson

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/awesome-learning#35]
**Is your feature request related to a problem? Please describe.**
Users navigating to our site should be able to quickly return to their last visited lesson if they visited one. 

**Describe the solution you'd like**
If a user has visited a lesson and clicked either the pre-reads, exercise button, or interact with the quiz, we should pop a toast when they come back to awesome learning to return to their last location. Likely we should store some information in local session data. 

**Describe alternatives you've considered**
We could not rely on engagement and only pop the toast if they have navigated to a lesson. 

Should use the toast built in #82

**Comment by lopeselio** [comment]
Hey 
@Cooperbuilt  @SheaBelsky  I would like to work with you guys on this project! 
Thank you and I am lookinbg forward to get started.
Best Regards 
Elio

**Comment by StanFaas** [comment]
First part of the implementation should be fixed by #103 .
Whenever the toast notifications are done I'll make sure the users sees their last course whenever they come back to the homepage.
