### ISSUE TITLE
Add Design Library for Shared Components

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/awesome-learning#49]
**Is your feature request related to a problem? Please describe.**
We currently have a number of general-purpose shared components, but no documentation on them. As more developers come into the fold, it would be helpful to have a library of these components and their expected usages.

**Describe the solution you'd like**
Add either styleguidist or storybook to this repo to document the general use components.

**Comment by ssamaresh** [comment]
picking this issue up.

**Comment by Cooperbuilt** [comment]
It's all yours
