### ISSUE TITLE
Move all shared components to a "shared components" folder

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/awesome-learning#50]
**Is your feature request related to a problem? Please describe.**
We should streamline this repo in terms of folder structure to make future development easier. In this case, not knowing which components are part of our "design library" could lead to replication and wheel re-invention. 

**Describe the solution you'd like**
Create a "shared components" folder
Move all shared components under the shared folder.

**Additional context**
Shared components aren't necessarily easy to spot. The obvious ones like buttons and section titles are easy. For any component that is on the fence, please create an issue to make the component more general and move to the shared components folder.

**Comment by juancarlosqr** [comment]
Hi, happy Hacktoberfest!

This is my first year, so I'm glad to participate. I would like to contribute to your project and work on this issue

I have experience with React and just a little with Gatsby.

Open to any questions and I will wait to be assigned to start working on this! Thanks

**Comment by SheaBelsky** [comment]
@Cooperbuilt I saw you had an open PR for this (#99). Do you plan on continuing you work for that branch?

**Comment by Cooperbuilt** [comment]
Im going to un-assign myself and let you take it @juancarlosqr!

**Comment by juancarlosqr** [comment]
Ok, great! Thanks

**Comment by juancarlosqr** [comment]
Hi @Cooperbuilt, you've got a PR!

Open to changes, comments, feedback or all of them!
