### ISSUE TITLE
Max-width CSS for the platform

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#58]
**Describe the bug**
On large resolutions, Awesome Learning stretches to the width of the monitor. We should constrain the width of the page up to a certain point (960px? Open to suggestions)

**Screenshots**
![Screen Shot 2019-09-27 at 3 29 19 PM](https://user-images.githubusercontent.com/15164473/65796815-99226900-e13b-11e9-8dac-0c7fd2992c98.png)

**Comment by leira-sanchez** [comment]
Why shouldn't it stretch the whole width?

**Comment by SheaBelsky** [comment]
@leira-sanchez On larger screens, it's hard to read the content of the webpage if the content takes up everything that it can. It reduces eyestrain and the amount of real estate that a visitor needs to physically read in order to digest what's on a page.

**Comment by DerekDenHartigh** [comment]
couldn't you just target the body for a set width via media query?  e.g.

CSS: 
@media screen and (min-width:960px) {
    body { max-width: 960px !important; }
}

**Comment by SheaBelsky** [comment]
that would be the idea. It would only take effect for larger browsers, smaller browsers who need all of the width will not be affected. I think we already have some sort of max width for our lesson page, just want to make sure it gets put on other pages as well.

**Comment by Prateek93a** [comment]
Can I work on this?

**Comment by Prateek93a** [comment]
Can I work on this for the Hacktoberfest contest?

**Comment by SheaBelsky** [comment]
Yes, feel free to go for it @Prateek93a !

**Comment by Prateek93a** [comment]
Thanks

**Comment by SheaBelsky** [comment]
@Prateek93a Are you still working on this issue? If not, please let me know, so that I can unassign you from this issue.

**Comment by shreegowtham27** [comment]
Hai, Please check the PR [#116](https://github.com/wayfair/awesome-learning/pull/116) have made the tweak, I have added the size as 80%

**Comment by Prateek93a** [comment]
@SheaBelsky Sorry Sir I am not currently working on it. Kindly assign it to someone else.
