### ISSUE TITLE
Remove `react-test-renderer` from dependencies

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/awesome-learning#59]
## Problem
We have a small contingency of tests that use `react-test-renderer` and take snapshots of the entire output. This is bad practice and should be removed.

## Acceptance Criteria
1. Remove all tests using react-test-renderer
2. Keep track of all removed tests
3. Add a list of removed test files to #21 as a comment
4. Remove the `react-test-renderer` from our dependencies list.

**Comment by Eshno** [comment]
Would like to take this 🙂

**Comment by SheaBelsky** [comment]
@Eshno This one is yours, thank you!

**Comment by SheaBelsky** [comment]
Resolved by #84
