### ISSUE TITLE
Reduce need to import SCSS variables/mixins in every file

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#61]
For our SCSS files, we have many cases where we need to import the `variables` and `mixins` files. 

```
@import '../../assets/scss/variables';
@import '../../assets/scss/mixins';
```

This makes SCSS files harder to iterate on for the following reasons:

1. We need to know where these two files are in relation to the current SCSS file
2. If the location of the current file changes, these two imports need to be changed
3. If the location of the variables or mixins file changes, every dependent SCSS file needs to be changed too

Ideally, these two import statements should be handled in one place only, so that engineers working on SCSS files can assume that these variables and mixins are always available to them (versus needing to be imported every time.)

**Comment by wpalacios** [comment]
I would like to do this one.

**Comment by SheaBelsky** [comment]
@wpalacios it's yours!

**Comment by wpalacios** [comment]
> @wpalacios it's yours!

Nice! Thanks!

**Comment by wpalacios** [comment]
@SheaBelsky mate, the issue is done! I just created a pull request here: [https://github.com/wayfair/awesome-learning/pull/68](url) 

Feel free to review it and approve it when you have some time. 

Thanks again for giving the opportunity to contribute to your project. 

Cheers and Happy Hacktober Fest!

**Comment by SheaBelsky** [comment]
Just merged it in! Thank you again for contributing! I posted a bunch of other issues earlier today, so feel free to pick up any more issues if you'd like!

**Comment by wpalacios** [comment]
Hi mate @SheaBelsky , sadly this pull request did not count for the Hacktober fest since we merged before October 1st. could you be so kind to revert the pull request so I can create a new one that counts for the Hacktober fest?

**Comment by SheaBelsky** [comment]
@wpalacios Unfortunately reverting it would cause a host of other issues with existing PRs. You're more than welcome to pick up another issue for it to count towards Hacktoberfest!
