### ISSUE TITLE
Going back to page 1 when paginating courses returns to the home page

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#63]
**Describe the bug**
If pagination is necessary for the lessons (https://wayfair.github.io/awesome-learning/courses), and a visitor tries to return to Page 1, it instead returns the visitor to the Awesome Learning home page.

**To Reproduce**
1. In `./config.js`, change `coursesPerPage` to 6 (or some number lower than 7)
2. `npm run develop`
3. Go to `/courses`
4. At the bottom of the page, click to the next page in the pagination element
5. Try to go back to page 1

**Expected behavior**
Pagination will actually return to Page 1 of the list of courses.

It's possible this is an inherent flaw in how we are doing our pagination. I don't think we actually have pagination for anything yet, but it would be helpful to experiment with forcing pagination for non-course things (tags or categories) to see if the issue exists for those types of components too.

**Comment by mazsam** [comment]
I will take this issue @SheaBelsky

**Comment by SheaBelsky** [comment]
This one is yours @mazsam !

**Comment by mazsam** [comment]
Thanks @SheaBelsky
