### ISSUE TITLE
Create helpful 404 page

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#64]
**Is your feature request related to a problem? Please describe.**
As a visitor to the website, I get frustrated when I access a page that doesn't exist and don't get any useful information about what to do.

**Describe the solution you'd like**
A meaningful 404 page that has better design and content than our current solution. We would like to provide visitors with the following:

- A helpful message that they've hit a page that doesn't exist. Use the below text:
```
It looks like you've tried to access a page that doesn't exist. It's possible that what you were looking for may have moved to another location, or it wasn't here to begin with.

Browse our [course catalog] to preview what subjects Awesome Learning currently offers.

You can also browse individual lessons [by tag] to dive right into an individual lesson.
```

The text [in brackets] should link to the corresponding page.

Courses page: `/courses`

Tags page: `/tags`

**Additional context**
Our current 404 page can be found at `src/templates/not-found-template.js` (and a corresponding test at `src/templates/not-found-template.test.js). Make sure the snapshot test is updated (as this page is purely presentational. If this page becomes interactive, please add more comprehensive unit testing around features.)

**Comment by charanjit-singh** [comment]
I'd like to do it.

**Comment by SheaBelsky** [comment]
@charanjit-singh It's all yours!

**Comment by Vectormike** [comment]
I was just about to do it haha

**Comment by Cooperbuilt** [comment]
@Vectormike if there are any other issues you see, or features you would like to add please feel free to open an issue or jump on one we already have, we really value your enthusiasm!

**Comment by saipasha** [comment]
I'd like to give it a try as well :))

**Comment by Cooperbuilt** [comment]
@charanjit-singh are you still working on this? We have a few other folks who are also interested.

**Comment by perun-01** [comment]
i could create one. is it still open??

**Comment by Cooperbuilt** [comment]
Hey @perun-01 I'm going to assign it to you because we haven't heard back from the other dev.

**Comment by perun-01** [comment]
getting errors while performing npm run develop
![Screenshot from 2019-10-17 22-51-34](https://user-images.githubusercontent.com/43863911/67033567-b0011d80-f133-11e9-8336-720c3e5f2eb9.png)
