### ISSUE TITLE
The tags page replaces browser history, does not add to it

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#65]
**Describe the bug**
Clicking a link [on our tags page](https://wayfair.github.io/awesome-learning/tags) replaces the current browser location, instead of adding to browser history.

**To Reproduce**
1. Open a new browser tab (to make this bug more obvious)
2. Go to https://wayfair.github.io/awesome-learning/tags
3. Click on a link
4. Try to go back in the browser

**Expected behavior**
You should be brought back to the list of tags, not to the "new tab" page for your browser

**Comment by devevignesh** [comment]
I would like to claim this

**Comment by mazsam** [comment]
Can i take this issue @SheaBelsky ?

**Comment by SheaBelsky** [comment]
@devevignesh I already assigned you an issue, so I'm going to assign this one to @mazsam . Thank you both for expressing interest!

**Comment by mazsam** [comment]
Hi @SheaBelsky, just trying step to reproduce, but can't reproduce it. 
Here this demo: https://www.loom.com/share/3e498a5b21f14fd292c719c323ee821b

**Comment by SheaBelsky** [comment]
Hmmm, that's bizarre. Might be something weird on my end. I'll try to reproduce it again, and if I can't I'll close the issue.

**Comment by mazsam** [comment]
@SheaBelsky Let me know if you still find this bug, i will try fix it as far as i can.

**Comment by devevignesh** [comment]
@mazsam Hey, could you check the same in Chrome Canary.

**Comment by Ipshu41** [comment]
@SheaBelsky I tried to reproduce the bug but its not replacing the browser history

**Comment by SheaBelsky** [comment]
Cannot reproduce, closing!
