### ISSUE TITLE
Address bar URLs should not be case sensitive

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#66]
**Describe the bug**
Some of our URLs in the address bar are case sensitive. 

**To Reproduce**
1. Go to https://wayfair.github.io/awesome-learning/courses/React-Hooks/intro-to-react-hooks
2. Change `React-Hooks` to `react-hooks`

**Expected behavior**
The page should still load the course for React Hooks.

**Additional context**
This probably has to do with GraphQL taking the browser query and matching it exactly. If this search could be made case-insensitively, it would probably solve the issue.

**Comment by Vectormike** [comment]
I will take this. But the only solution is to change all courses in page-data/courses to small letters.

**Comment by SheaBelsky** [comment]
Ah, I see the file names have capital letters in them. If you need to change those to make this happen, that's fine. Ideally the query itself would be case insensitive (if that's possible with GraphQL). I'm concerned that changing the file names without supporting capital letters will break old page links, though.

**Comment by Eshno** [comment]
We could change every slug to complete lower case slugs, but the issue would still persist if we were to enter the slug with any capital letter. In addition to this in case it's a bother, I'd suggest to redirect those urls with capital letters within them to their full lower case version of them.

**Comment by SheaBelsky** [comment]
It looks like we could set the input data (slug) to be case insensitive to be case-insensitive before it comes into GraphQL, in addition to @Eshno  and @Vectormike 's suggestions. That way, case sensitive queries would still work, but we force the input to be lowercase before it's checked against the lesson pages. It looks like GraphQL queries are case sensitive, and there isn't a way to make it case insensitive.

https://github.com/wayfair/awesome-learning/blob/master/gatsby/create-pages.js#L82

Before we pass the input data into `createPage`, `edge.node.fields.slug` should be lowercase. That way, uppercase versions of the query will still work. We should do this for *all* pages (courses, lessons, quizzes, general pages) in addition to courses.

**Comment by Eshno** [comment]
At the moment the only way i found to receive a full lower case URL from the client is to add `window.location.replace(window.location.href.toLowerCase());` here https://github.com/wayfair/awesome-learning/blob/master/gatsby-browser.js
This would work as a redirect.
This by itself would loop infinitely so one should add a condition such like `window.location.href.match(/[A-Z]/g)`. But probably there's a better way to do this.

**Comment by SheaBelsky** [comment]
We shouldn't need a redirect if we just make the input parameter to the query lowercase before anything happens. The page should still be accessible from the old link with capital letters, but it would match the GraphQL query after the names of the files (and titles of the files in `/content/courses`) are made to be lowercase.

**Comment by Vectormike** [comment]
So, on on-create-node file I 
`if (node.frontmatter.course) {
      // console.log(JSON.stringify(node, undefined, 4));
      const slug = path.dirname(node.fileAbsolutePath);
      // console.log('@@@@@@@@@', slug);
      createNodeField({
        node,
        name: 'slug',
        value: slug
      });
    }`

Shouldn't this be creating a new slug?

**Comment by Cooperbuilt** [comment]
This doc provides more info on how slugs are generated here https://www.gatsbyjs.org/packages/gatsby-source-filesystem/

Here is a guide for programmatically creating slugs from pages (which is what we are doing )
https://www.gatsbyjs.org/tutorial/part-seven/

Here's a custom slug package that might be useful
https://www.gatsbyjs.org/packages/gatsby-plugin-slug/

Hopefully these help on your quest!
