### ISSUE TITLE
Course list should always be sorted alphabetically

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#69]
**Describe the bug**
Our ordering of courses is arbitrary, and should be sorted alphabetically (ascending, A-Z).

**To Reproduce**
1. Go to https://wayfair.github.io/awesome-learning/courses/
2. Observe that the ordering of courses does not follow a meaningful pattern

**Expected behavior**
Courses should be sorted alphabetically to make it easier for visitors to find a course they are looking for

**Comment by BalSharma** [comment]
Let me try it. Can I pick this up?

**Comment by SheaBelsky** [comment]
@BalSharma It's all yours!

**Comment by jaysiee** [comment]
Sorry, for the confusion. I decided to work on this and I didn't see that @BalSharma decided to work on this as well. I pushed my changes anyway, feel free to pick the solution you like better (no hard feelings 😄  ).

**Comment by BalSharma** [comment]
I did not know that someone already working on the issue. I am sorry @jaysiee. Please go ahead @jaysiee. I have just forked it, done nothing. I am stepping out.

**Comment by Cooperbuilt** [comment]
@BalSharma please feel free to jump on another issue, or to make your own issue if you see anything we should improve. We are so appreciative of your enthusiasm!
