### ISSUE TITLE
Fix GitHub icon, remove unused icons

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#70]
**Describe the bug**
The GitHub icon is currently flipped (the tail is on the left side of the Octocat, it should be on the right side.)

**To Reproduce**
1. Go to https://wayfair.github.io/awesome-learning/
2. Look in the top-right of the browser

**Expected behavior**
The GitHub icon should display correctly

**Additional context**
<img width="275" alt="Screen Shot 2019-09-29 at 9 03 04 AM" src="https://user-images.githubusercontent.com/15164473/65832866-f29faa80-e297-11e9-86c0-bdc7f45c5a0a.png">

At the same time that we fix this icon, let's also remove other icons too. We can delete the following icons:

- vkontakte
- telegram
- rss

You'll need to edit `src/utils/get-icon.js` and `src/constants/icons.js` to make this work.

**Comment by YogaSakti** [comment]
can i take this issue??

**Comment by SheaBelsky** [comment]
@YogaSakti It's yours! Thank you for taking it!

**Comment by YogaSakti** [comment]
it's okay to wait until 1 october? because it's for hacktoberfest

**Comment by SheaBelsky** [comment]
Yep, that's totally fine!

**Comment by SheaBelsky** [comment]
Resolved by #98
