### ISSUE TITLE
Buttons on small devices do not contain all of their content

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#71]
**Describe the bug**
Buttons on smaller devices do not contain all of their content if there is a lot of it.

**To Reproduce**
1. View the Awesome Learning site on mobile (or Inspect Element and emulate a mobile device)
2. Go to https://wayfair.github.io/awesome-learning/courses/Testing/
3. Scroll to the bottom of the page

**Expected behavior**
Buttons should contain all of their contents, rather than having text overflow from the bottom of the button vertically. 

**Screenshots**
<img width="251" alt="Screen Shot 2019-09-29 at 9 06 57 AM" src="https://user-images.githubusercontent.com/15164473/65832942-c0427d00-e298-11e9-8e93-7cf7e7b42607.png">

**Additional context**
When implementing this fix, make sure our existing buttons are not affected!

**Comment by Arnoldicus** [comment]
Hi. i can take this issue too :)

**Comment by SheaBelsky** [comment]
@Arnoldicus You already have an issue or two assigned. I'd love to see if someone else can take this issue. If you complete the work from your other issues before that happens, I'll assign this to you.

**Comment by Arnoldicus** [comment]
@SheaBelsky It's already done, but if you don't mind i will open pull request at 1 October :)

**Comment by Arnoldicus** [comment]
@SheaBelsky Opened merge request for this issue :)

**Comment by SheaBelsky** [comment]
Resolved by #90
