### ISSUE TITLE
Excessive space on some pages for small devices

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#72]
**Describe the bug**
On small devices, there is an excessive amount of space between the last of the content and the actual end of the page.

**To Reproduce**
1. Go to any page on mobile (https://wayfair.github.io/awesome-learning/courses/Testing/testing-workshop/)
2. Scroll to the bottom of the page

**Expected behavior**
The end of the page should be much closer to the actual end of the page, rather than there being an excessive amount of space

**Screenshots**
<img width="299" alt="Screen Shot 2019-09-29 at 9 11 27 AM" src="https://user-images.githubusercontent.com/15164473/65832979-24654100-e299-11e9-9955-46890f9901fe.png">

**Additional context**
We want a small amount of space at the end of the page, but not as much as there is. When you create a PR to fix this issue, include a screenshot of what the new amount of space is.

**Comment by Arnoldicus** [comment]
Hi there. Can you assign this issue on me?

**Comment by SheaBelsky** [comment]
@Arnoldicus It's yours, thank you so much!

**Comment by Arnoldicus** [comment]
@SheaBelsky Hi! Just opened merge request for this issue
