### ISSUE TITLE
YouTube embeds on small devices create horizontal overflow

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#73]
**Describe the bug**
On small devices, embedding any YouTube video forces the page to expand its horizontal width to be much larger than is necessary.

**To Reproduce**
1. Go to any course page on mobile (https://wayfair.github.io/awesome-learning/courses/Testing/testing-workshop/) or the How To page (https://wayfair.github.io/awesome-learning/howTo)
2. Go to the YouTube video

**Expected behavior**
The YouTube video should appear with the correct amount of width on mobile, not an arbitrarily large value.

**Screenshots**
<img width="333" alt="Screen Shot 2019-09-29 at 9 12 49 AM" src="https://user-images.githubusercontent.com/15164473/65833033-93429a00-e299-11e9-93d3-83448975401c.png">

**Additional context**
We currently have the width of the video derived from an attribute on the `iframe` itself. Ideally, the height and width should derive from SCSS (and controlled from a media query so that the width can change itself on mobile, and then be locked to a certain width on larger devices.) Keep the width that we have for large devices and tablets, but for mobile devices, constrain the width to be some percentage of the screen width.

It may be worthwhile to create a React component that consumes the YouTube video ID, and formats everything as necessary (versus leaving the details up to the engineer, these could be addressed with a React Component.)

**Comment by SheaBelsky** [comment]
This can also be seen on our "How To" page: https://wayfair.github.io/awesome-learning/howTo

**Comment by mazsam** [comment]
@SheaBelsky could you assign this to me ? Thank You

**Comment by SheaBelsky** [comment]
@mazsam You already have an issue or two assigned. I'd love to see if someone else can take this issue. If you complete the work from your other issues before that happens, I'll assign this to you.

**Comment by SheaBelsky** [comment]
Resolved by #91
