### ISSUE TITLE
Clicking on the title of a lesson should navigate to it

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#74]
**Is your feature request related to a problem? Please describe.**
As a visitor to the site, I get frustrated when clicking the title of a lesson does not navigate to it. I should not be constrained to only clicking the button below the title to navigate to a lesson.

**Describe the solution you'd like**
Clicking the title of a lesson should navigate to it, in addition to the existing behavior of "Click to learn [lesson title]"

**Additional context**
Go to https://wayfair.github.io/awesome-learning/courses/Data-Types/ and click any lesson title. It should go to the lesson page, but it currently does not.

**Comment by sowmiyamuthuraman** [comment]
can I work on this?

**Comment by SheaBelsky** [comment]
@sowmiyamuthuraman Go for it!
