### ISSUE TITLE
Update browser color for mobile devices

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#77]
**Describe the bug**
On mobile, Awesome Learning changes the color of the browser to orange. It should instead be changed to our primary color (`#2b416a`).

**To Reproduce**
1. Go to Awesome Learning on mobile (https://wayfair.github.io/awesome-learning/)

**Expected behavior**
The color of the browser should not be orange. You want to change the hex value of `theme_color` in `./gatsby-config.js`

**Screenshots**
![Screenshot_20190929-111313](https://user-images.githubusercontent.com/15164473/65834573-3f8c7c80-e2aa-11e9-8b2f-6d1dca26f5af.png)

**Comment by mazsam** [comment]
Could you assign to me for this issue @SheaBelsky ?
Thank You.

**Comment by triyasniko** [comment]
may i try solving this problem @SheaBelsky ?

**Comment by SheaBelsky** [comment]
@mazsam You already have an assigned issue, so I'm going to assign this one to @triyasniko. Thank you both for your interest!

**Comment by triyasniko** [comment]
i'm so sorry sir @SheaBelsky , i can't run this repo on my localcomputer.. 
so You can give this assignment to others

**Comment by mazsam** [comment]
I can do it @triyasniko @SheaBelsky

**Comment by mazsam** [comment]
@SheaBelsky could you update what's browser your using ? thank you!

**Comment by TyLippe** [comment]
If no one is assigned this one I would love to take a swing at it!

**Comment by SheaBelsky** [comment]
Resolved via #96
