### ISSUE TITLE
Back to "course name" should not be hypethenated

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#78]
**Is your feature request related to a problem? Please describe.**
When viewing an individual lesson, going back to a course represents the name of the course with hyphens (`functions-and-scope` instead of `functions and scope`)

**Describe the solution you'd like**
The link to return to the course, from the lesson, should not have hyphens in it.

Look in the `src/components/Lesson/Lesson.js` file to see where we currently create this link. See if we can get the non-hyphen version of the course with the GraphQL query in `lesson-template.js`

**Comment by deepansh946** [comment]
@SheaBelsky I would like to work on this issue.

**Comment by SheaBelsky** [comment]
@deepansh946 It's yours to work on, thank you!

**Comment by deepansh946** [comment]
@SheaBelsky One proposed solution for the link is to make it in camel case. Will it be fine?

**Comment by SheaBelsky** [comment]
What part of the link needs to be in camel case? Do you mean the text itself? The text itself is showing as all uppercase, so that should not be the issue.
