### ISSUE TITLE
Create a shared "toast" component

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/awesome-learning#82]
**Is your feature request related to a problem? Please describe.**
We need an intuitive piece of UI to show user interaction results. Toast notifications are known UX patterns we could use for a few use cases. For example, when a user completes a pre-read quiz. 

**Describe the solution you'd like**
Build a shared, tested component that can take on multiple states given a prop. It should have 4 possible states 
  
![toast](https://user-images.githubusercontent.com/15932239/65842661-092b1d80-e2fb-11e9-9556-83056555ef2f.jpg)

It should also take text as children.

**Comment by perceptron007** [comment]
@Cooperbuilt Do you want the implementation in Plain JS? or HTML /CSS?

**Comment by Cooperbuilt** [comment]
Hey @perceptron007, our repo is built in React, so I would prefer to see this built using React with a subtle css animation of the toast when it enters and exits the page. 

Here are some css animation guidelines. 

## Entering and Leaving
A toast should enter in slower than it exits out. A slower entrance draws attention to the toast, and a quick exit limits distraction.

## Animation Variables
### Entering: 
Deceleration is best for an entering element, here is a decelerating cubic bezier for the entrance animation.
`cubic-bezier(.22, .61, .36, 1)`

#### Exiting
Acceleration is best for an exiting element. Here is an accelerating cubic bezier for your exiting elements.
`cubic-bezier(.55, .06, .68, .19)`

**Comment by gemanepa** [comment]
@perceptron007 are you taking it? :P If not, I would like to develop it in React

**Comment by Cooperbuilt** [comment]
@gemanepa I'm going to assign this to you, have fun!

**Comment by Cooperbuilt** [comment]
Any progress @gemanepa? If you have stopped working on this I would like to un-assign it and give a chance to someone else who may want to build this feature. Just let me know

**Comment by gemanepa** [comment]
Hi @Cooperbuilt . Between my job and college right now I'm not working on it, I was planning to do it after October 20 but if you want to reassign it to someone else, yeah go ahead and do it. If that person ends up not doing it I'll work on it at the end of the month

**Comment by gemanepa** [comment]
@Cooperbuilt Is there a site or library where you would like me to get the five icons I need? Or from anywhere is just fine?

**Comment by gemanepa** [comment]
@Cooperbuilt do you want the toast to close automatically after x seconds by default?

**Comment by Cooperbuilt** [comment]
We can open another issue if users want the toast to auto dismiss
