### ISSUE TITLE
Create a course carousel component for the landing page

### ISSUE THREAD

**Issue by Cooperbuilt** [wayfair/awesome-learning#83]
**Is your feature request related to a problem? Please describe.**
We list only four of our courses on our landing page, but users sould have some way of knowing all of our courses. If we include a carousel that cycles through cards of all our courses, users will be able to know what courses we have as soon as they land

**Describe the solution you'd like**
I think a stripe like this underneath the blue section on the landing page would be ideal

![Slice 1](https://user-images.githubusercontent.com/15932239/65843241-9623a600-e2fe-11e9-931f-384bb4203f4b.png)

It should be powered by GraphQL and contain all of the courses we currently have on AL, and whenever anyone adds a new course, this component should also include that. The course cards in the carousel themselves should mimic the ones in the "hero" section of the landing page

**Implementation Details**
This carousel should be accessible and fully tested.

**Comment by xitter** [comment]
@Cooperbuilt I would like to take this up, could you assign this to me?

**Comment by xitter** [comment]
@Cooperbuilt The icon(name) and subtitle data in the current cards are not available on the GraphQL. IMO, these should be put on the server. What do you think?

**Comment by Cooperbuilt** [comment]
@xitter I will open up some new issues, but this one is done. Nice work!
