### ISSUE TITLE
Generate PropTypes for all files

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#9]
We currently do an inconsistent job of checking props using `PropTypes`. It would be great to have better `PropTypes` validations, to guard against component/query changes that result in unexpected behaior.

**Comment by cengizhanbasak** [comment]
I am working on it now.

**Comment by StanFaas** [comment]
Ran my NodeJS script through your project and with that added missing PropTypes.

**Comment by cengizhanbasak** [comment]
https://github.com/wayfair/awesome-learning/pull/101
